### ISSUE TITLE
AGW Terminal Window Closure does not Disconnect Session - Crashes

### ISSUE THREAD

**Issue by pe1rrr** [pe1rrr/qttermtcp#1]
Test:

> QtTerm 0.0.0.39
> Enabled AGW
> Disable AGW Monitor
> Close AGW Monitor Window (it keeps opening regardless of Setting it OFF, another bug?)
> Open New terminal window
> Initiate Connect to station on Port 1 of qtSoundModem
> Connection Established
> Close Terminal Window

No disconnect occurs, and a moment later QtTermTCP fully crashes.

```
Thread 1 "piQtTermTCP" received signal SIGSEGV, Segmentation fault.
0xb6c70740 in QTextEdit::textCursor() const ()
--Type <RET> for more, q to quit, c to continue without paging--
   from /usr/lib/arm-linux-gnueabihf/libQt5Widgets.so.5
(gdb) bt
#0  0xb6c70740 in QTextEdit::textCursor() const ()
    at /usr/lib/arm-linux-gnueabihf/libQt5Widgets.so.5
#1  0x0001c684 in WritetoMonWindow(Ui_ListenSession*, unsigned char*, int)
    (Sess=Sess@entry=0x1a29410, Msg=0x1a86b58 "*** PE1RRR-14 Connected to CMS\r", 
    Msg@entry=0x28c14 <ProcessReceivedData(Ui_ListenSession*, unsigned char*, int)+812> "\244\377\377\352Q\f\207\342\006 \240\341\005\020\240\341\034", len=len@entry=31) at QtTermTCP.cpp:2080
#2  0x00028c14 in ProcessReceivedData(Ui_ListenSession*, unsigned char*, int)
    (Sess=0x1a29410, Buffer=0x28c14 <ProcessReceivedData(Ui_ListenSession*, unsigned char*, int)+812> "\244\377\377\352Q\f\207\342\006 \240\341\005\020\240\341\034", len=len@entry=31) at TermTCPCommon.cpp:193
#3  0x000319d8 in on_AGW_D_frame(int, char*, char*, unsigned char*, int)
    (snd_ch=<optimized out>, CallFrom=CallFrom@entry=0x1a86b3c "CT1EBQ-10", CallTo=CallTo@entry=0x1a86b46 "PE1RRR-14", Msg=<optimized out>, Len=31)
    at AGWCode.cpp:1076
#4  0x00031fa0 in AGW_Process_Input(AGWUser_t*) (AGW=AGW@entry=0x1a86b30)
    at AGWCode.cpp:1485
#5  0x000320d0 in QtTermTCP::AGWreadyRead() (this=<optimized out>)
    at AGWCode.cpp:377
#6  0x00032e94 in QtTermTCP::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
--Type <RET> for more, q to quit, c to continue without paging--
out>) at moc_QtTermTCP.cpp:289
#7  0xb6190244 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5
#8  0xb648411c in  () at /usr/lib/arm-linux-gnueabihf/libQt5Network.so.5

```

**Comment by pe1rrr** [comment]
During a session using an AGW connected station, and a combined terminal monitor window, it was not possible to disconnect the station due to the disconnect menu being greyed out. In addition, there was no monitored traffic displayed in this combined window. 

Demo:

**Comment by pe1rrr** [comment]
Version 0.0.0.42 appears to resolve this issue.
