### ISSUE TITLE
It is possible to initiate connect in AGW monitor window (bug)

### ISSUE THREAD

**Issue by pe1rrr** [pe1rrr/qttermtcp#2]
As per the title, it is possible to initiate a connect accidentally from the AGW monitor window meaning a session will start and commence in that window. Since it is not a terminal/interactive it is not possible to disconnect the remote station.

Steps:

- Fresh QtTermTCP setup
- Set up AGW
- Highlight the monitor window on the desktop with the mouse/cursor
- Initiate a Connect from the Connect->AGW menu.

Demo: https://youtu.be/-lwlU0UiYeY

**Comment by pe1rrr** [comment]
```

Thread 1 "piQtTermTCP" received signal SIGBUS, Bus error.
0xb6770844 in QTextCursor::QTextCursor(QTextCursor const&) ()
   from /usr/lib/arm-linux-gnueabihf/libQt5Gui.so.5
(gdb) bt
#0  0xb6770844 in QTextCursor::QTextCursor(QTextCursor const&) ()
   from /usr/lib/arm-linux-gnueabihf/libQt5Gui.so.5
#1  0xb6cabd20 in QWidgetTextControl::textCursor() const ()
   from /usr/lib/arm-linux-gnueabihf/libQt5Widgets.so.5
#2  0xb6c8b758 in QTextEdit::textCursor() const ()
   from /usr/lib/arm-linux-gnueabihf/libQt5Widgets.so.5
#3  0x0001cd68 in WritetoOutputWindowEx (Sess=0x3efc38, Sess@entry=0x37aed8, 
    Buffer=Buffer@entry=0x370cd0 "*** PE1RRR-14 Connected to CMS\r", 
    len=len@entry=31, termWindow=0x49000, 
    OutputSaveLen=OutputSaveLen@entry=0x37afec, 
    OutputSave=OutputSave@entry=0x37aff0 "", Colour=Colour@entry=23)
    at QtTermTCP.cpp:1902
#4  0x0001d48c in WritetoOutputWindow (Sess=Sess@entry=0x37aed8, 
    Buffer=Buffer@entry=0x370cd0 "*** PE1RRR-14 Connected to CMS\r", 
    len=len@entry=31) at QtTermTCP.cpp:1865
#5  0x00028aa4 in ProcessReceivedData (Sess=0x37aed8, 
    Buffer=0x28aa4 <ProcessReceivedData(Ui_ListenSession*, unsigned char*, int)+444> "", len=len@entry=31) at TermTCPCommon.cpp:372
#6  0x000319d8 in on_AGW_D_frame (snd_ch=<optimized out>, 
    CallFrom=CallFrom@entry=0x370cb4 "CT1EBQ-10", 
    CallTo=CallTo@entry=0x370cbe "PE1RRR-14", Msg=<optimized out>, Len=31)
    at AGWCode.cpp:1076
#7  0x00031fa0 in AGW_Process_Input (AGW=AGW@entry=0x370ca8)
--Type <RET> for more, q to quit, c to continue without paging--
   
#8  0x000320d0 in QtTermTCP::AGWreadyRead (this=<optimized out>)
    at AGWCode.cpp:377
#9  0x00032e94 in QtTermTCP::qt_static_metacall (_o=<optimized out>, 
    _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at moc_QtTermTCP.cpp:289
#10 0xb61ab244 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5
#11 0xb649f11c in ?? () from /usr/lib/arm-linux-gnueabihf/libQt5Network.so.5
```

Clicking Disconnect results in the above.

**Comment by pe1rrr** [comment]
Version 0.0.0.42 resolves this issue although it is still possible to (accidentally) initiate a connect from within a monitor-only window.
